from enum import Enum
import pygame
#Window
GAME_NAME = "CROSSWORD"
WINDOW_HEIGHT = 840
WINDOW_WIDTH = 1000

#Menu
MENU_HEIGHT = WINDOW_HEIGHT
MENU_WIDTH = WINDOW_WIDTH - WINDOW_HEIGHT
MENU_FONT_SIZE = 20
MENU_BUTTON_WIDTH = 2*(MENU_WIDTH // 3)
MENU_BUTTON_HEIGHT = MENU_HEIGHT // 18

#Board
BOARD_SIZE = 10
BOARD_WIDTH = BOARD_HEIGHT = WINDOW_HEIGHT

#Drawing
OFFSET = 2
LINE_WIDTH = 4

#Enums
STATES = Enum("STATES", "START PLAYING FINISHED")
BUTTONS = Enum("BUTTONS", "NEW_GAME CHECK HELP EXIT")

